# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_gari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gari',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
