# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200124_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gari',
            name='price',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
