# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200124_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gari',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gari',
            name='model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='gari',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
