# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200124_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gari',
            name='brand',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gari',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gari',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
