# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200124_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gari',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
